Update examples with v6.0.0 changes

diff --git a/examples/react-firebase-redux/.github/workflows/deploy.yml b/examples/react-firebase-redux/.github/workflows/deploy.yml
--- a/examples/react-firebase-redux/.github/workflows/deploy.yml
+++ b/examples/react-firebase-redux/.github/workflows/deploy.yml
@@ -7,8 +7,8 @@ on:
       - prod
 
 jobs:
-  build:
-    name: Build
+  deploy:
+    name: Deploy
     runs-on: ubuntu-latest
     steps:
       - name: Checkout Repo
@@ -19,58 +19,132 @@ jobs:
         with:
           node-version: 10
 
-      - name: Get yarn cache
-        id: yarn-cache
-        run: echo "::set-output name=dir::$(yarn cache dir)"
+      - name: Get Library Versions For Binary Caching
+        id: cache-settings
+        run: |
+          echo "::set-output name=dir::$(yarn cache dir)"
 
-      - name: Cache npm dependencies
+      - name: Cache App Dependencies
         uses: actions/cache@v1
         with:
-          path: ${{ steps.yarn-cache.outputs.dir }}
-          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
+          path: ${{ steps.cache-settings.outputs.dir }}
+          key: ${{ runner.os }}-app-${{ hashFiles('yarn.lock') }}
 
       - name: Install Dependencies
         env:
-          CI: true
           CYPRESS_INSTALL_BINARY: 0 # Skip install of Cypress (handled in its own job)
           HUSKY_SKIP_INSTALL: 1 # Skip install of Husky
         run: |
           yarn install --frozen-lockfile
           yarn --cwd functions install --frozen-lockfile
 
+      - name: Set App Environment Settings
+        env:
+          MASTER_SERVICE_ACCOUNT: ${{ secrets.MASTER_SERVICE_ACCOUNT }}
+          PROD_SERVICE_ACCOUNT: ${{ secrets.PROD_SERVICE_ACCOUNT }}
+          GITHUB_HEAD_REF: ${{ github.head_ref }}
+          GITHUB_REF: ${{ github.ref }}
+          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
+        run: |
+          set -o pipefail
+
+          # Throw a clear error if FIREBASE_TOKEN secret is not set
+          if [ -z "$FIREBASE_TOKEN" ];
+            then
+              errMsg="\"FIREBASE_TOKEN\" github secret is required to load project configuration. Visit https://github.com/${{ github.repository }}/settings/secrets to set."
+              echo "::error ::$errMsg"
+              exit 1
+          fi
+
+          # Get branch name from github ref (i.e. refs/heads/master -> master)
+          gitBranch=${GITHUB_REF##*/}
+
+          # Find the config associated to the firebase project in .firebaserc (falling back to default)
+          gcloudProject=$(cat .firebaserc | jq -r --arg alias "$gitBranch" '.projects[$alias] // .projects.default')
+          appName=react-firebase-redux
+          echo "Setting environment for branch: $gitBranch, project: $gcloudProject, and app: $appName..."
+
+          # Set variables to environment to be used in later steps
+          echo "::set-env name=GCLOUD_PROJECT::$gcloudProject"
+
+          # Get value of Service Account associated with branch (i.e. STAGE_SERVICE_ACCOUNT)
+          branchPrefix=$(echo $gitBranch | tr a-z A-Z | tr - _)
+          branchSaKey="${branchPrefix}_SERVICE_ACCOUNT"
+          branchSa=$(eval echo \$${branchSaKey})
+          if [[ ! -z "${branchSa}" ]]; then
+            echo Using service account with key \"$branchSaKey\"
+            serviceAccount=$branchSa
+          else
+            echo Falling back to service account with key "DEVELOP_SERVICE_ACCOUNT"
+            serviceAccount=$DEVELOP_SERVICE_ACCOUNT
+          fi
+
+          echo "Service Account selected for projectId $(echo $serviceAccount | jq .project_id)"
+
+          # Generate Service Account file required to prevent credential error during functions unit tests (jq used to format)
+          echo "Generating Service Account File..."
+          echo "$(echo $serviceAccount | jq .)" > $HOME/serviceAccount.json
+          echo "::set-env name=GOOGLE_APPLICATION_CREDENTIALS::$HOME/serviceAccount.json"
+
+          # Use Firebase SDK API to get the app's configuration and export to REACT_APP prefixed environment variables
+          # NOTE: databaseURL is intentionally removed since it is set above
+          firebaseConfig=$(npx firebase --project $gcloudProject apps:sdkconfig WEB \
+            $(npx firebase --project $gcloudProject apps:list WEB | grep $appName | awk '{ print $4}') | \
+              tr '\n' ' ' | \
+              sed 's/.*initializeApp(//g' | \
+              sed 's/);//g' | \
+              jq -r 'to_entries[] | [.key, (.value | tojson)] | join("::")' | \
+              sed 's/:"/:/g; s/^/echo \"::set-env name=REACT_APP_FIREBASE_/g' \
+          )
+
+          # Loop through each line of config and evaluate to export env vars
+          while IFS= read -r line; do
+            echo Evaluating: $line
+            eval $line
+          done <<< "$firebaseConfig"
+
       - name: Verify App
         run: |
-          yarn build:config # Create env specific src/config.js
           yarn lint # Check for lint in app code
-          yarn build # Build app bundles
 
-      - name: Verify Functions
+      - name: Build Functions
         run: |
-          yarn --cwd functions build
+          yarn functions:build
 
+      - name: Build App
+        run: |
+          yarn build
+
+      # Archive build in case it needs to be downloaded later for debugging
       - name: Archive Build Artifact
-        uses: actions/upload-artifact@master
+        uses: actions/upload-artifact@v2
         with:
           name: build
           path: build
-
-      - name: Archive Functions Artifact
-        uses: actions/upload-artifact@master
-        with:
-          name: functions-build
-          path: functions/dist
 
       - name: Deploy to Firebase
         env:
           FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
           GITHUB_REF: ${{ github.ref }}
           GITHUB_HEAD_REF: ${{ github.head_ref }}
+        # Deploy to project associated with branch name alias in .firebaserc.
+        # Force flag is used to automatically delete any removed cloud functions
         run: |
-          $(yarn bin)/firebase-ci deploy -s
+          $(yarn bin)/firebase-ci deploy -s --force
 
-      - name: Archive Debug Log
-        uses: actions/upload-artifact@master
-        if: failure()
+      - name: Check if version has been updated
+        if: github.ref == 'refs/heads/prod'
+        id: check
+        uses: EndBug/version-check@v1
+
+      - name: Create Release
+        if: github.ref == 'refs/heads/prod' && steps.check.outputs.changed == 'true'
+        id: create_release
+        uses: actions/create-release@v1
+        env:
+          GITHUB_TOKEN: ${{ github.token }}
         with:
-          name: firebase-debug
-          path: firebase-debug.log
+          tag_name: v${{ env.PACKAGE_VERSION }}
+          release_name: v${{ env.PACKAGE_VERSION }}
+          draft: false
+          prerelease: false
diff --git a/examples/react-firebase-redux/.github/workflows/verify.yml b/examples/react-firebase-redux/.github/workflows/verify.yml
--- a/examples/react-firebase-redux/.github/workflows/verify.yml
+++ b/examples/react-firebase-redux/.github/workflows/verify.yml
@@ -1,4 +1,4 @@
-name: Verify App
+name: Verify
 
 on: [pull_request]
 
@@ -15,52 +15,109 @@ jobs:
         with:
           node-version: 10
 
-      - name: Get yarn cache
-        id: yarn-cache
-        run: echo "::set-output name=dir::$(yarn cache dir)"
+      - name: Get Library Versions For Binary Caching
+        id: cache-settings
+        run: |
+          echo "::set-output name=dir::$(yarn cache dir)"
 
-      - name: Cache npm dependencies
+      - name: Cache App Dependencies
         uses: actions/cache@v1
         with:
-          path: ${{ steps.yarn-cache.outputs.dir }}
-          key: ${{ runner.os }}-app-${{ hashFiles('**/yarn.lock') }}
+          path: ${{ steps.cache-settings.outputs.dir }}
+          key: ${{ runner.os }}-app-${{ hashFiles('yarn.lock') }}
 
       - name: Install Dependencies
         env:
-          CI: true
           CYPRESS_INSTALL_BINARY: 0 # Skip install of Cypress (handled in its own job)
           HUSKY_SKIP_INSTALL: 1 # Skip install of Husky
         run: |
           yarn install --frozen-lockfile
           yarn --cwd functions install --frozen-lockfile
 
-      - name: Set Environment Settings
+      - name: Set App Environment Settings
+        env:
+          SERVICE_ACCOUNT: ${{ secrets.MASTER_SERVICE_ACCOUNT }}
+          GITHUB_HEAD_REF: ${{ github.head_ref }}
+          GITHUB_REF: ${{ github.ref }}
+          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
         run: |
+          set -o pipefail
+
+          # Throw a clear error if FIREBASE_TOKEN secret is not set
+          if [ -z "$FIREBASE_TOKEN" ];
+            then
+              missingTokenErrMsg="\"FIREBASE_TOKEN\" github secret is required to load project configuration. Visit https://github.com/${{ github.repository }}/settings/secrets to set."
+              echo "::error ::$missingTokenErrMsg"
+              exit 1
+          fi
+
+          # Throw a clear error if MASTER_SERVICE_ACCOUNT secret is not set
+          if [ -z "$SERVICE_ACCOUNT" ];
+            then
+              missingSaErrMsg="\"MASTER_SERVICE_ACCOUNT\" github secret is required to run functions unit tests. Visit https://github.com/${{ github.repository }}/settings/secrets to set."
+              echo "::error ::$missingSaErrMsg"
+              exit 1
+          fi
+
+          # Get branch name from github ref (i.e. refs/heads/master -> master)
+          gitBranch=${GITHUB_REF##*/}
+
+          # Find the config associated to the firebase project in .firebaserc (falling back to default)
+          gcloudProject=$(cat .firebaserc | jq -r --arg alias "$gitBranch" '.projects[$alias] // .projects.default')
+          appName=react-firebase-redux
+          echo "Setting environment for branch: $gitBranch, project: $gcloudProject, and app: $appName..."
+
           echo "Setting emulator settings to environment..."
-          echo "::set-env name=REACT_APP_FIREBASE_DATABASE_EMULATOR_HOST::localhost:$(cat firebase.json | jq .emulators.database.port)"
-          echo "::set-env name=REACT_APP_FIRESTORE_EMULATOR_HOST::localhost:$(cat firebase.json | jq .emulators.firestore.port)"
+          databaseEmulatorHost=localhost:$(cat firebase.json | jq .emulators.database.port)
+          emulatorHost=localhost:$(cat firebase.json | jq .emulators.firestore.port)
+          
+          # Set variables to environment to be used in later steps
+          echo "::set-env name=REACT_APP_FIREBASE_DATABASE_EMULATOR_HOST::$databaseEmulatorHost"
+          echo "::set-env name=REACT_APP_FIRESTORE_EMULATOR_HOST::$emulatorHost"
+          echo "::set-env name=REACT_APP_FB_databaseURL::http://$databaseEmulatorHost?ns=$gcloudProject"
+          echo "::set-env name=GCLOUD_PROJECT::$gcloudProject"
+
+          # Generate Service Account file required to prevent credential error during functions unit tests (jq used to format)
+          echo "Generating Service Account File..."
+          echo "$(echo $SERVICE_ACCOUNT | jq .)" > $HOME/serviceAccount.json
+          echo "::set-env name=GOOGLE_APPLICATION_CREDENTIALS::$HOME/serviceAccount.json"
+
+          # Use Firebase SDK API to get the app's configuration and export to REACT_APP prefixed environment variables
+          # NOTE: databaseURL is intentionally removed since it is set above
+
+          # Use firebase SDK API to get the app's configuration and export to CYPRESS. NOTE: databaseURL is intentionally removed
+          firebaseConfig=$(npx firebase --project $gcloudProject apps:sdkconfig WEB \
+            $(npx firebase --project $gcloudProject apps:list WEB | grep $appName | awk '{ print $4}') | \
+              tr '\n' ' ' | \
+              sed 's/.*initializeApp(//g' | \
+              sed 's/);//g' | \
+              jq -r 'del(.databaseURL) | to_entries[] | [.key, (.value | tojson)] | join("::")' | \
+              sed 's/:"/:/g; s/^/echo \"::set-env name=REACT_APP_FIREBASE_/g' \
+          )
+
+          # Loop through each line of config and evaluate to export env vars
+          while IFS= read -r line; do
+            echo Evaluating: $line
+            eval $line
+          done <<< "$firebaseConfig"
 
       - name: Verify App
         run: |
-          yarn build:config # Create env specific src/config.js
           yarn lint # Check for lint in app code
-          yarn build # Build app bundles
 
-      - name: Verify Functions
+      - name: Build Functions
         run: |
-          yarn --cwd functions build
+          yarn functions:build
+
+      - name: Build App
+        run: |
+          yarn build
 
       - name: Archive Build Artifact
-        uses: actions/upload-artifact@master
+        uses: actions/upload-artifact@v2
         with:
           name: build
           path: build
-
-      - name: Archive Functions Artifact
-        uses: actions/upload-artifact@master
-        with:
-          name: functions-build
-          path: functions/dist
 
   ui-tests:
     name: UI Tests
@@ -79,8 +136,8 @@ jobs:
         id: cache-settings
         run: |
           echo "::set-output name=dir::$(yarn cache dir)"
-          echo "::set-output name=firebase-tools::$(yarn info firebase-tools version --silent)"
-          echo "::set-output name=cypress::$(yarn info cypress version --silent)"
+          echo "::set-output name=firebase-tools::$(yarn list -s --depth=0 --pattern firebase-tools | tail -n 1 | sed 's/.*@//g')"
+          echo "::set-output name=cypress::$(yarn list -s --depth=0 --pattern cypress | tail -n 1 | sed 's/.*@//g')"
 
       - name: Cache Firebase Emulator Binaries
         uses: actions/cache@v1
@@ -98,11 +155,10 @@ jobs:
         uses: actions/cache@v1
         with:
           path: ${{ steps.cache-settings.outputs.dir }}
-          key: ${{ runner.os }}-app-${{ hashFiles('yarn.lock') }}
+          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
 
       - name: Install Dependencies
         env:
-          CI: true
           HUSKY_SKIP_INSTALL: 1 # Skip install of Husky
         run: |
           yarn install --frozen-lockfile
@@ -110,38 +166,41 @@ jobs:
 
       - name: Set Test Environment Settings
         env:
-          SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}
+          SERVICE_ACCOUNT: ${{ secrets.MASTER_SERVICE_ACCOUNT }}
           FIREBASE_APP_NAME: ${{ secrets.FIREBASE_APP_NAME }}
           GITHUB_HEAD_REF: ${{ github.head_ref }}
           GITHUB_REF: ${{ github.ref }}
         run: |
           set -o pipefail
 
-          export GIT_BRANCH=${GITHUB_REF##*/}
-          export GCLOUD_PROJECT=$(cat .firebaserc | jq -r --arg GIT_BRANCH "$GIT_BRANCH" '.projects[$GIT_BRANCH] // .projects.default')
-          echo "::set-env name=GCLOUD_PROJECT::$GCLOUD_PROJECT"
-          echo "Environment set for branch: $GIT_BRANCH and project: $GCLOUD_PROJECT"
+          gitBranch=${GITHUB_REF##*/}
+          gcloudProject=$(cat .firebaserc | jq -r --arg alias "$gitBranch" '.projects[$alias] // .projects.default')
+          echo "Setting environment for branch: $gitBranch and project: $gcloudProject"
   
           echo "Setting emulator settings to environment..."
-          export FIREBASE_DATABASE_EMULATOR_HOST=localhost:$(cat firebase.json | jq .emulators.database.port)
-          export FIRESTORE_EMULATOR_HOST=localhost:$(cat firebase.json | jq .emulators.firestore.port)
-          echo "::set-env name=FIREBASE_DATABASE_EMULATOR_HOST::$FIREBASE_DATABASE_EMULATOR_HOST"
-          echo "::set-env name=FIRESTORE_EMULATOR_HOST::$FIRESTORE_EMULATOR_HOST"
+          databaseEmulatorHost=localhost:$(cat firebase.json | jq .emulators.database.port)
+          emulatorHost=localhost:$(cat firebase.json | jq .emulators.firestore.port)
+
+          # Set variables to environment to be used in later steps
+          echo "::set-env name=FIREBASE_DATABASE_EMULATOR_HOST::$databaseEmulatorHost"
+          echo "::set-env name=FIRESTORE_EMULATOR_HOST::$emulatorHost"
           echo "::set-env name=CYPRESS_BASE_URL::http://localhost:$(cat package.json | jq .config.port)"
-          echo "::set-env name=CYPRESS_FB_databaseURL::http://$FIREBASE_DATABASE_EMULATOR_HOST?ns=$GCLOUD_PROJECT"
+          echo "::set-env name=CYPRESS_FB_databaseURL::http://$databaseEmulatorHost?ns=$gcloudProject"
+          echo "::set-env name=GCLOUD_PROJECT::$gcloudProject"
   
+          # Generate Service Account file required to prevent credential error during functions unit tests (jq used to format)
           echo "Generating Service Account File..."
           echo "$(echo $SERVICE_ACCOUNT | jq .)" > $HOME/serviceAccount.json
           echo "::set-env name=GOOGLE_APPLICATION_CREDENTIALS::$HOME/serviceAccount.json"
 
           # Use firebase SDK API to get the app's configuration and export to CYPRESS. NOTE: databaseURL is intentionally removed
-          firebaseConfig=$(npx firebase --project $GCLOUD_PROJECT apps:sdkconfig WEB \
-            $(npx firebase --project $GCLOUD_PROJECT apps:list WEB | grep $FIREBASE_APP_NAME | awk '{ print $4}') | \
+          firebaseConfig=$(npx firebase --project $gcloudProject apps:sdkconfig WEB \
+            $(npx firebase --project $gcloudProject apps:list WEB | grep $FIREBASE_APP_NAME | awk '{ print $4}') | \
               tr '\n' ' ' | \
               sed 's/.*initializeApp(//g' | \
               sed 's/);//g' | \
               jq -r 'del(.databaseURL) | to_entries[] | [.key, (.value | tojson)] | join("::")' | \
-              sed 's/:"/:/g; s/^/echo \"::set-env name=CYPRESS_FB_/g' \
+              sed 's/:"/:/g; s/^/echo \"::set-env name=CYPRESS_FIREBASE_/g' \
           )
 
           # Loop through each line of config and evaluate to export env vars
@@ -152,7 +211,7 @@ jobs:
 
       # Download Built app since we are testing locally
       - name: Download Build Artifact
-        uses: actions/download-artifact@master
+        uses: actions/download-artifact@v2
         with:
           name: build
           path: build
@@ -164,13 +223,11 @@ jobs:
         uses: cypress-io/github-action@v1
         with:
           record: true
-          group: 'E2E Tests'
-          start: yarn emulate --project $GCLOUD_PROJECT
-          wait-on: http://localhost:3000
-          # wait for 3 minutes for the server to respond
-          wait-on-timeout: 180
+          start: yarn emulators:hosting --project ${{ env.GCLOUD_PROJECT }}
+          wait-on: ${{ env.CYPRESS_BASE_URL }}
+          # wait for 2 minutes for the server to respond
+          wait-on-timeout: 120
         env:
-          CI: true
           # pass the Dashboard record key as an environment variable
           CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_KEY }}
           CYPRESS_TEST_UID: ${{ secrets.TEST_UID }}
diff --git a/examples/react-firebase/.github/workflows/verify.yml b/examples/react-firebase/.github/workflows/verify.yml
--- a/examples/react-firebase/.github/workflows/verify.yml
+++ b/examples/react-firebase/.github/workflows/verify.yml
@@ -1,4 +1,4 @@
-name: Verify App
+name: Verify
 
 on: [pull_request]
 
@@ -15,50 +15,106 @@ jobs:
         with:
           node-version: 10
 
-      - name: Get yarn cache
-        id: yarn-cache
-        run: echo "::set-output name=dir::$(yarn cache dir)"
+      - name: Get Library Versions For Binary Caching
+        id: cache-settings
+        run: |
+          echo "::set-output name=dir::$(yarn cache dir)"
 
-      - name: Cache npm dependencies
+      - name: Cache App Dependencies
         uses: actions/cache@v1
         with:
-          path: ${{ steps.yarn-cache.outputs.dir }}
-          key: ${{ runner.os }}-app-${{ hashFiles('**/yarn.lock') }}
+          path: ${{ steps.cache-settings.outputs.dir }}
+          key: ${{ runner.os }}-app-${{ hashFiles('yarn.lock') }}
 
       - name: Install Dependencies
         env:
-          CI: true
           CYPRESS_INSTALL_BINARY: 0 # Skip install of Cypress (handled in its own job)
           HUSKY_SKIP_INSTALL: 1 # Skip install of Husky
         run: |
           yarn install --frozen-lockfile
           yarn --cwd functions install --frozen-lockfile
 
-      - name: Set Environment Settings
+      - name: Set App Environment Settings
+        env:
+          SERVICE_ACCOUNT: ${{ secrets.MASTER_SERVICE_ACCOUNT }}
+          GITHUB_HEAD_REF: ${{ github.head_ref }}
+          GITHUB_REF: ${{ github.ref }}
+          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
         run: |
+          set -o pipefail
+
+          # Throw a clear error if FIREBASE_TOKEN secret is not set
+          if [ -z "$FIREBASE_TOKEN" ];
+            then
+              missingTokenErrMsg="\"FIREBASE_TOKEN\" github secret is required to load project configuration. Visit https://github.com/${{ github.repository }}/settings/secrets to set."
+              echo "::error ::$missingTokenErrMsg"
+              exit 1
+          fi
+
+          # Throw a clear error if MASTER_SERVICE_ACCOUNT secret is not set
+          if [ -z "$SERVICE_ACCOUNT" ];
+            then
+              missingSaErrMsg="\"MASTER_SERVICE_ACCOUNT\" github secret is required to run functions unit tests. Visit https://github.com/${{ github.repository }}/settings/secrets to set."
+              echo "::error ::$missingSaErrMsg"
+              exit 1
+          fi
+
+          # Get branch name from github ref (i.e. refs/heads/master -> master)
+          gitBranch=${GITHUB_REF##*/}
+
+          # Find the config associated to the firebase project in .firebaserc (falling back to default)
+          gcloudProject=$(cat .firebaserc | jq -r --arg alias "$gitBranch" '.projects[$alias] // .projects.default')
+          appName=react-firebase
+          echo "Setting environment for branch: $gitBranch, project: $gcloudProject, and app: $appName..."
+
           echo "Setting emulator settings to environment..."
-          echo "::set-env name=REACT_APP_FIREBASE_DATABASE_EMULATOR_HOST::localhost:$(cat firebase.json | jq .emulators.database.port)"
-          echo "::set-env name=REACT_APP_FIRESTORE_EMULATOR_HOST::localhost:$(cat firebase.json | jq .emulators.firestore.port)"
+          databaseEmulatorHost=localhost:$(cat firebase.json | jq .emulators.database.port)
+          emulatorHost=localhost:$(cat firebase.json | jq .emulators.firestore.port)
+          
+          # Set variables to environment to be used in later steps
+          echo "::set-env name=REACT_APP_FIREBASE_DATABASE_EMULATOR_HOST::$databaseEmulatorHost"
+          echo "::set-env name=REACT_APP_FIRESTORE_EMULATOR_HOST::$emulatorHost"
+          echo "::set-env name=REACT_APP_FB_databaseURL::http://$databaseEmulatorHost?ns=$gcloudProject"
+          echo "::set-env name=GCLOUD_PROJECT::$gcloudProject"
+
+          # Generate Service Account file required to prevent credential error during functions unit tests (jq used to format)
+          echo "Generating Service Account File..."
+          echo "$(echo $SERVICE_ACCOUNT | jq .)" > $HOME/serviceAccount.json
+          echo "::set-env name=GOOGLE_APPLICATION_CREDENTIALS::$HOME/serviceAccount.json"
+
+          # Use Firebase SDK API to get the app's configuration and export to REACT_APP prefixed environment variables
+          # NOTE: databaseURL is intentionally removed since it is set above
+
+          # Use firebase SDK API to get the app's configuration and export to CYPRESS. NOTE: databaseURL is intentionally removed
+          firebaseConfig=$(npx firebase --project $gcloudProject apps:sdkconfig WEB \
+            $(npx firebase --project $gcloudProject apps:list WEB | grep $appName | awk '{ print $4}') | \
+              tr '\n' ' ' | \
+              sed 's/.*initializeApp(//g' | \
+              sed 's/);//g' | \
+              jq -r 'del(.databaseURL) | to_entries[] | [.key, (.value | tojson)] | join("::")' | \
+              sed 's/:"/:/g; s/^/echo \"::set-env name=REACT_APP_FIREBASE_/g' \
+          )
+
+          # Loop through each line of config and evaluate to export env vars
+          while IFS= read -r line; do
+            echo Evaluating: $line
+            eval $line
+          done <<< "$firebaseConfig"
 
       - name: Verify App
         run: |
-          yarn build:config # Create env specific src/config.js
           yarn lint # Check for lint in app code
-          yarn build # Build app bundles
 
-      - name: Verify Functions
+      - name: Build Functions
         run: |
-          yarn --cwd functions test:cov # Run unit tests with coverage
-          yarn --cwd functions build
+          yarn functions:build
+
+      - name: Build App
+        run: |
+          yarn build
 
       - name: Archive Build Artifact
-        uses: actions/upload-artifact@master
+        uses: actions/upload-artifact@v2
         with:
           name: build
           path: build
-
-      - name: Archive Functions Artifact
-        uses: actions/upload-artifact@master
-        with:
-          name: functions-build
-          path: functions/dist
diff --git a/examples/react-firestore/.github/workflows/deploy.yml b/examples/react-firestore/.github/workflows/deploy.yml
--- a/examples/react-firestore/.github/workflows/deploy.yml
+++ b/examples/react-firestore/.github/workflows/deploy.yml
@@ -7,8 +7,8 @@ on:
       - prod
 
 jobs:
-  build:
-    name: Build
+  deploy:
+    name: Deploy
     runs-on: ubuntu-latest
     steps:
       - name: Checkout Repo
@@ -35,7 +35,7 @@ jobs:
         uses: actions/cache@v1
         with:
           path: ${{ steps.cache-settings.outputs.dir }}
-          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
+          key: ${{ runner.os }}-app-${{ hashFiles('yarn.lock') }}
 
       - name: Install Dependencies
         env:
@@ -47,24 +47,56 @@ jobs:
 
       - name: Set App Environment Settings
         env:
+          MASTER_SERVICE_ACCOUNT: ${{ secrets.MASTER_SERVICE_ACCOUNT }}
+          PROD_SERVICE_ACCOUNT: ${{ secrets.PROD_SERVICE_ACCOUNT }}
           GITHUB_HEAD_REF: ${{ github.head_ref }}
           GITHUB_REF: ${{ github.ref }}
           FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
         run: |
           set -o pipefail
 
+          # Throw a clear error if FIREBASE_TOKEN secret is not set
+          if [ -z "$FIREBASE_TOKEN" ];
+            then
+              errMsg="\"FIREBASE_TOKEN\" github secret is required to load project configuration. Visit https://github.com/${{ github.repository }}/settings/secrets to set."
+              echo "::error ::$errMsg"
+              exit 1
+          fi
+
+          # Get branch name from github ref (i.e. refs/heads/master -> master)
           gitBranch=${GITHUB_REF##*/}
 
           # Find the config associated to the firebase project in .firebaserc (falling back to default)
-          gcloudProject=$(cat .firebaserc | jq -r --arg alias "$projectAlias" '.projects[$alias] // .projects.default')
+          gcloudProject=$(cat .firebaserc | jq -r --arg alias "$gitBranch" '.projects[$alias] // .projects.default')
+          appName=react-firestore
+          echo "Setting environment for branch: $gitBranch, project: $gcloudProject, and app: $appName..."
 
-          echo Setting configuration from the \"$gcloudProject\" Firebase project...
-
+          # Set variables to environment to be used in later steps
           echo "::set-env name=GCLOUD_PROJECT::$gcloudProject"
 
-          # Use firebase SDK API to get the app's configuration and export to CYPRESS. NOTE: databaseURL is intentionally removed
-          firebaseConfig=$(npx firebase --project $GCLOUD_PROJECT apps:sdkconfig WEB \
-            $(npx firebase --project $GCLOUD_PROJECT apps:list WEB | grep $FIREBASE_APP_NAME | awk '{ print $4}') | \
+          # Get value of Service Account associated with branch (i.e. STAGE_SERVICE_ACCOUNT)
+          branchPrefix=$(echo $gitBranch | tr a-z A-Z | tr - _)
+          branchSaKey="${branchPrefix}_SERVICE_ACCOUNT"
+          branchSa=$(eval echo \$${branchSaKey})
+          if [[ ! -z "${branchSa}" ]]; then
+            echo Using service account with key \"$branchSaKey\"
+            serviceAccount=$branchSa
+          else
+            echo Falling back to service account with key "DEVELOP_SERVICE_ACCOUNT"
+            serviceAccount=$DEVELOP_SERVICE_ACCOUNT
+          fi
+
+          echo "Service Account selected for projectId $(echo $serviceAccount | jq .project_id)"
+
+          # Generate Service Account file required to prevent credential error during functions unit tests (jq used to format)
+          echo "Generating Service Account File..."
+          echo "$(echo $serviceAccount | jq .)" > $HOME/serviceAccount.json
+          echo "::set-env name=GOOGLE_APPLICATION_CREDENTIALS::$HOME/serviceAccount.json"
+
+          # Use Firebase SDK API to get the app's configuration and export to REACT_APP prefixed environment variables
+          # NOTE: databaseURL is intentionally removed since it is set above
+          firebaseConfig=$(npx firebase --project $gcloudProject apps:sdkconfig WEB \
+            $(npx firebase --project $gcloudProject apps:list WEB | grep $appName | awk '{ print $4}') | \
               tr '\n' ' ' | \
               sed 's/.*initializeApp(//g' | \
               sed 's/);//g' | \
@@ -81,16 +113,25 @@ jobs:
       - name: Verify App
         run: |
           yarn lint # Check for lint in app code
-          yarn build # Build app bundles
 
-      - name: Verify Functions
-        run: |
-          yarn --cwd functions test:cov # Run unit tests with coverage
-          yarn --cwd functions build
+      # NOTE: Skipped because of "Channel credentials must be a ChannelCredentials object" error from firebase-admin
+      # See https://github.com/firebase/firebase-tools/issues/2207 for more info
+      # - name: Unit Test Functions
+      #   run: |
+      #     yarn functions:test:cov -- --project $GCLOUD_PROJECT # Run unit tests with coverage
 
-      - name: Upload Test Coverage For Functions
+      # - name: Upload Test Coverage For Functions
+      #   # NOTE: Token will need to be added if using codecov with private repos
+      #   run: |
+      #     bash <(curl -s https://codecov.io/bash) -f functions/coverage/lcov.info || echo 'Codecov failed to upload'
+
+      - name: Build Functions
         run: |
-          bash <(curl -s https://codecov.io/bash) -f functions/coverage/lcov.info || echo 'Codecov failed to upload'
+          yarn functions:build
+
+      - name: Build App
+        run: |
+          yarn build
 
       # Archive build in case it needs to be downloaded later for debugging
       - name: Archive Build Artifact
@@ -108,25 +149,6 @@ jobs:
         # Force flag is used to automatically delete any removed cloud functions
         run: |
           $(yarn bin)/firebase-ci deploy -s --force
-          echo "::set-env name=PACKAGE_VERSION::$(cat package.json | jq -r '.version')"
-
-      # TODO: Uncomment after setting SENTRY_AUTH_TOKEN secret and confirming org and project name
-      # - name: Upload SourceMaps to Sentry
-      #   env:
-      #     SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
-      #     SENTRY_ORG: prescottprue
-      #     SENTRY_PROJECT: react-firestore
-      #   run: |
-      #     gitBranch=${GITHUB_REF##*/}
-      #     envName=$(if [ $gitBranch == "master" ]; then echo staging; else echo $gitBranch; fi;)
-      #     releaseSuffix=$envName@$PACKAGE_VERSION
-      #     releaseName=react-firestore-$releaseSuffix
-      #     echo Creating Sentry release \"$releaseName\" for project \"$SENTRY_PROJECT\"...
-      #     $(yarn bin)/sentry-cli releases new $releaseName --finalize
-      #     echo Uploading source maps to Sentry release...
-      #     $(yarn bin)/sentry-cli releases files $releaseName upload-sourcemaps ./build/static/js --no-rewrite
-      #     echo Associating commits with the Sentry release...
-      #     $(yarn bin)/sentry-cli releases set-commits --auto $version
 
       - name: Check if version has been updated
         if: github.ref == 'refs/heads/prod'
@@ -144,3 +166,30 @@ jobs:
           release_name: v${{ env.PACKAGE_VERSION }}
           draft: false
           prerelease: false
+
+      - name: Create Release In Sentry
+        env:
+          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
+          SENTRY_ORG: prescottprue
+          SENTRY_PROJECT: react-firestore
+        run: |
+          # Throw a clear error if SENTRY_AUTH_TOKEN secret is not set
+          if [ -z "$SENTRY_AUTH_TOKEN" ];
+            then
+              warningMsg="\"SENTRY_AUTH_TOKEN\" github secret is required to create releases in Sentry. Visit https://github.com/${{ github.repository }}/settings/secrets to set."
+              echo "::warning ::$warningMsg"
+              exit 0
+          fi
+
+          envName=$(if [ $GIT_BRANCH == "master" ]; then echo staging; else echo $GIT_BRANCH; fi;)
+          releaseSuffix=$envName@$PACKAGE_VERSION
+          releaseName=react-firestore-$releaseSuffix
+
+          echo Creating Sentry release \"$releaseName\" for project \"$SENTRY_PROJECT\"...
+          $(yarn bin)/sentry-cli releases new $releaseName --finalize
+
+          echo Uploading source maps to Sentry release...
+          $(yarn bin)/sentry-cli releases files $releaseName upload-sourcemaps ./build/static/js --no-rewrite
+
+          echo Associating commits with the Sentry release...
+          $(yarn bin)/sentry-cli releases set-commits --auto $PACKAGE_VERSION
