* feat(app): switch error handler to npm package instead of script + window variable * fix(app): include Google Roboto font by default * fix(app): ignore correct test config file in hosting settings

diff --git a/generators/app/templates/.github/workflows/deploy.yml b/generators/app/templates/.github/workflows/deploy.yml
--- a/generators/app/templates/.github/workflows/deploy.yml
+++ b/generators/app/templates/.github/workflows/deploy.yml
@@ -7,8 +7,8 @@ on:
       - prod
 
 jobs:
-  build:
-    name: Build
+  deploy:
+    name: Deploy
     runs-on: ubuntu-latest
     steps:
       - name: Checkout Repo
@@ -53,18 +53,28 @@ jobs:
         run: |
           set -o pipefail
 
+          # Throw a clear error if FIREBASE_TOKEN secret is not set
+          if [ -z "$FIREBASE_TOKEN" ];
+            then
+              errMsg="\"FIREBASE_TOKEN\" github secret is required to load project configuration. Visit https://github.com/${{ github.repository }}/settings/secrets to set."
+              echo "::error ::$errMsg"
+              exit 1
+          fi
+
+          # Get branch name from github ref (i.e. refs/heads/master -> master)
           gitBranch=${GITHUB_REF##*/}
 
           # Find the config associated to the firebase project in .firebaserc (falling back to default)
           gcloudProject=$(cat .firebaserc | jq -r --arg alias "$projectAlias" '.projects[$alias] // .projects.default')
+          appName=<%= appName %>
 
-          echo Setting configuration from the \"$gcloudProject\" Firebase project...
+          echo Setting configuration from the \"$gcloudProject\" Firebase Project and \"$appName\" App...
 
           echo "::set-env name=GCLOUD_PROJECT::$gcloudProject"
 
           # Use firebase SDK API to get the app's configuration and export to CYPRESS. NOTE: databaseURL is intentionally removed
-          firebaseConfig=$(npx firebase --project $GCLOUD_PROJECT apps:sdkconfig WEB \
-            $(npx firebase --project $GCLOUD_PROJECT apps:list WEB | grep $FIREBASE_APP_NAME | awk '{ print $4}') | \
+          firebaseConfig=$(npx firebase --project $gcloudProject apps:sdkconfig WEB \
+            $(npx firebase --project $gcloudProject apps:list WEB | grep $appName | awk '{ print $4}') | \
               tr '\n' ' ' | \
               sed 's/.*initializeApp(//g' | \
               sed 's/);//g' | \
@@ -85,8 +95,8 @@ jobs:
 
       - name: Verify Functions
         run: |
-          <% if(includeFunctionsTests) { %>yarn --cwd functions test:cov # Run unit tests with coverage
-          <% } %>yarn --cwd functions build<% } %><% if(includeFunctionsTests) { %>
+          <% if(includeFunctionsTests) { %>yarn functions:test:cov # Run unit tests with coverage
+          <% } %>yarn functions:build<% } %><% if(includeFunctionsTests) { %>
 
       - name: Upload Test Coverage For Functions
         run: |
@@ -114,18 +124,28 @@ jobs:
         run: |
           set -o pipefail
 
+          # Throw a clear error if FIREBASE_TOKEN secret is not set
+          if [ -z "$FIREBASE_TOKEN" ];
+            then
+              errMsg="\"FIREBASE_TOKEN\" github secret is required to load project configuration. Visit https://github.com/${{ github.repository }}/settings/secrets to set."
+              echo "::error ::$errMsg"
+              exit 1
+          fi
+
+          # Get branch name from github ref (i.e. refs/heads/master -> master)
           gitBranch=${GITHUB_REF##*/}
 
           # Find the config associated to the firebase project in .firebaserc (falling back to default)
           gcloudProject=$(cat .firebaserc | jq -r --arg alias "$projectAlias" '.projects[$alias] // .projects.default')
+          appName=<%= appName %>
 
-          echo Setting configuration from the \"$gcloudProject\" Firebase project...
+          echo Setting configuration from the \"$gcloudProject\" Firebase Project and \"$appName\" App...
 
           echo "::set-env name=GCLOUD_PROJECT::$gcloudProject"
 
           # Use firebase SDK API to get the app's configuration and export to CYPRESS. NOTE: databaseURL is intentionally removed
-          firebaseConfig=$(npx firebase --project $GCLOUD_PROJECT apps:sdkconfig WEB \
-            $(npx firebase --project $GCLOUD_PROJECT apps:list WEB | grep $FIREBASE_APP_NAME | awk '{ print $4}') | \
+          firebaseConfig=$(npx firebase --project $gcloudProject apps:sdkconfig WEB \
+            $(npx firebase --project $gcloudProject apps:list WEB | grep $appName | awk '{ print $4}') | \
               tr '\n' ' ' | \
               sed 's/.*initializeApp(//g' | \
               sed 's/);//g' | \
@@ -146,8 +166,8 @@ jobs:
 
       - name: Verify Functions
         run: |
-          <% if(includeFunctionsTests) { %>npm run --prefix functions test:cov # Run unit tests with coverage
-          <% } %>npm run --prefix functions build<% } %>
+          <% if(includeFunctionsTests) { %>npm run functions:test:cov # Run unit tests with coverage
+          <% } %>npm run functions build<% } %>
 
       # Archive build in case it needs to be downloaded later for debugging
       - name: Archive Build Artifact
diff --git a/generators/app/templates/.github/workflows/verify.yml b/generators/app/templates/.github/workflows/verify.yml
--- a/generators/app/templates/.github/workflows/verify.yml
+++ b/generators/app/templates/.github/workflows/verify.yml
@@ -1,4 +1,4 @@
-name: Verify App
+name: Verify
 
 on: [pull_request]
 
@@ -49,12 +49,22 @@ jobs:
         run: |
           set -o pipefail
 
+          # Throw a clear error if FIREBASE_TOKEN secret is not set
+          if [ -z "$FIREBASE_TOKEN" ];
+            then
+              errMsg="\"FIREBASE_TOKEN\" github secret is required to load project configuration. Visit https://github.com/${{ github.repository }}/settings/secrets to set."
+              echo "::error ::$errMsg"
+              exit 1
+          fi
+
+          # Get branch name from github ref (i.e. refs/heads/master -> master)
           gitBranch=${GITHUB_REF##*/}
 
           # Find the config associated to the firebase project in .firebaserc (falling back to default)
           gcloudProject=$(cat .firebaserc | jq -r --arg alias "$projectAlias" '.projects[$alias] // .projects.default')
+          appName=<%= appName %>
 
-          echo Setting configuration from the \"$gcloudProject\" Firebase project...
+          echo Setting configuration from the \"$gcloudProject\" Firebase Project and \"$appName\" App...
 
           echo "::set-env name=GCLOUD_PROJECT::$gcloudProject"
 
@@ -67,8 +77,8 @@ jobs:
           echo "::set-env name=REACT_APP_FB_databaseURL::http://$databaseEmulatorHost?ns=$gcloudProject"
 
           # Use firebase SDK API to get the app's configuration and export to CYPRESS. NOTE: databaseURL is intentionally removed
-          firebaseConfig=$(npx firebase --project $GCLOUD_PROJECT apps:sdkconfig WEB \
-            $(npx firebase --project $GCLOUD_PROJECT apps:list WEB | grep $FIREBASE_APP_NAME | awk '{ print $4}') | \
+          firebaseConfig=$(npx firebase --project $gcloudProject apps:sdkconfig WEB \
+            $(npx firebase --project $gcloudProject apps:list WEB | grep $appName | awk '{ print $4}') | \
               tr '\n' ' ' | \
               sed 's/.*initializeApp(//g' | \
               sed 's/);//g' | \
@@ -89,8 +99,8 @@ jobs:
 
       - name: Verify Functions
         run: |
-          <% if(includeFunctionsTests) { %>yarn --cwd functions test:cov # Run unit tests with coverage
-          <% } %>yarn --cwd functions build<% } %><% if(includeFunctionsTests) { %>
+          <% if(includeFunctionsTests) { %>yarn functions:test:cov # Run unit tests with coverage
+          <% } %>yarn functions:build<% } %><% if(includeFunctionsTests) { %>
 
       - name: Upload Test Coverage For Functions
         run: |
@@ -118,14 +128,22 @@ jobs:
         run: |
           set -o pipefail
 
+          # Throw a clear error if FIREBASE_TOKEN secret is not set
+          if [ -z "$FIREBASE_TOKEN" ];
+            then
+              errMsg="\"FIREBASE_TOKEN\" github secret is required to load project configuration. Visit https://github.com/${{ github.repository }}/settings/secrets to set."
+              echo "::error ::$errMsg"
+              exit 1
+          fi
+
+          # Get branch name from github ref (i.e. refs/heads/master -> master)
           gitBranch=${GITHUB_REF##*/}
 
           # Find the config associated to the firebase project in .firebaserc (falling back to default)
           gcloudProject=$(cat .firebaserc | jq -r --arg alias "$projectAlias" '.projects[$alias] // .projects.default')
+          appName=<%= appName %>
 
-          echo Setting configuration from the \"$gcloudProject\" Firebase project...
-
-          echo "::set-env name=GCLOUD_PROJECT::$gcloudProject"
+          echo Setting configuration from the \"$gcloudProject\" Firebase Project and \"$appName\" App...
 
           echo "Setting emulator settings to environment..."
           databaseEmulatorHost=localhost:$(cat firebase.json | jq .emulators.database.port)
@@ -134,10 +152,11 @@ jobs:
           echo "::set-env name=REACT_APP_FIREBASE_DATABASE_EMULATOR_HOST::$databaseEmulatorHost"
           echo "::set-env name=REACT_APP_FIRESTORE_EMULATOR_HOST::$emulatorHost"
           echo "::set-env name=REACT_APP_FB_databaseURL::http://$databaseEmulatorHost?ns=$gcloudProject"
+          echo "::set-env name=GCLOUD_PROJECT::$gcloudProject"
 
           # Use firebase SDK API to get the app's configuration and export to CYPRESS. NOTE: databaseURL is intentionally removed
-          firebaseConfig=$(npx firebase --project $GCLOUD_PROJECT apps:sdkconfig WEB \
-            $(npx firebase --project $GCLOUD_PROJECT apps:list WEB | grep $FIREBASE_APP_NAME | awk '{ print $4}') | \
+          firebaseConfig=$(npx firebase --project $gcloudProject apps:sdkconfig WEB \
+            $(npx firebase --project $gcloudProject apps:list WEB | grep $appName | awk '{ print $4}') | \
               tr '\n' ' ' | \
               sed 's/.*initializeApp(//g' | \
               sed 's/);//g' | \
@@ -158,12 +177,8 @@ jobs:
 
       - name: Verify Functions
         run: |
-          <% if(includeFunctionsTests) { %>npm run --prefix functions test:cov # Run unit tests with coverage
-          <% } %>npm run --prefix functions build<% } %><% if(includeFunctionsTests) { %>
-
-      - name: Upload Test Coverage For Functions
-        run: |
-          bash <(curl -s https://codecov.io/bash) -f functions/coverage/lcov.info || echo 'Codecov failed to upload'<% } %>
+          <% if(includeFunctionsTests) { %>npm run functions:test:cov # Run unit tests with coverage
+          <% } %>npm run functions:build<% } %>
   
       - name: Archive Build Artifact
         uses: actions/upload-artifact@v2
