v8.0.0 (#371)
## Breaking Changes
* Drop support for node pre v12
* Switch to node 14 in CI workflows
* Update to Node 14 Runtime in cloud functions

## Features/Updates
* react-hook-form v6 to v7
* cypress v6 to v7
* Adding preview channel to verify workflow (with associated delete preview channel workflow which removes preview channel on merge)
* Update `husky` v4 to v6
* Update `yeoman-generator` from v4 to v5
* Update `yeoman-test` from v2 to v6

diff --git a/generators/app/templates/.github/workflows/verify.yml b/generators/app/templates/.github/workflows/verify.yml
--- a/generators/app/templates/.github/workflows/verify.yml
+++ b/generators/app/templates/.github/workflows/verify.yml
@@ -18,7 +18,7 @@ jobs:
       - name: Setup Node
         uses: actions/setup-node@v2.1.5
         with:
-          node-version: 12<% if(useYarn) { %>
+          node-version: 14<% if(useYarn) { %>
 
       - name: Get Library Versions For Binary Caching
         id: cache-settings
@@ -46,11 +46,24 @@ jobs:
           <% if(useYarn) { %>yarn install --frozen-lockfile<% } else { %>npm ci --loglevel error<% } %>
           <% if(useYarn) { %>yarn --cwd functions install --frozen-lockfile<% } else { %>npm --prefix functions ci --loglevel error<% } %>
 
-      - name: Set App Environment Settings
+      - name: Set environment
+        run: |
+          # Get branch name from github ref (i.e. refs/heads/master -> master)
+          gitBranch=${GITHUB_REF##*/}
+
+          # Find the config associated to the firebase project in .firebaserc (falling back to default)
+          gcloudProject=$(cat .firebaserc | jq -r --arg alias "$gitBranch" '.projects[$alias] // .projects.default')
+          appName=<%= appName %>
+
+          echo "Setting environment for branch: $gitBranch, project: $gcloudProject, and app: $appName..."
+
+          # Set variables to environment to be used in later steps
+          echo "GCLOUD_PROJECT=$gcloudProject" >> $GITHUB_ENV
+          echo "NODE_CONFIG_ENV=$branch" >> $GITHUB_ENV
+          echo "ENV=$branch" >> $GITHUB_ENV
+
+      - name: Generate Firebase SDK config for ${{ env.GCLOUD_PROJECT }}
         env:
-          SERVICE_ACCOUNT: ${{ secrets.MASTER_SERVICE_ACCOUNT }}
-          GITHUB_HEAD_REF: ${{ github.head_ref }}
-          GITHUB_REF: ${{ github.ref }}
           FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
         run: |
           set -o pipefail
@@ -63,55 +76,39 @@ jobs:
               exit 1
           fi
 
-          # Get branch name from github ref (i.e. refs/heads/master -> master)
-          gitBranch=${GITHUB_REF##*/}
-
-          # Find the config associated to the firebase project in .firebaserc (falling back to default)
-          gcloudProject=$(cat .firebaserc | jq -r --arg alias "$gitBranch" '.projects[$alias] // .projects.default')
-          appName=<%= appName %>
-          echo "Setting environment for branch: $gitBranch, project: $gcloudProject, and app: $appName..."
-
-          echo "Setting emulator settings to environment..."
-          databaseEmulatorHost=localhost:$(cat firebase.json | jq .emulators.database.port)
-          emulatorHost=localhost:$(cat firebase.json | jq .emulators.firestore.port)
-          
-          # Set variables to environment to be used in later steps
-          echo "REACT_APP_FIREBASE_DATABASE_EMULATOR_HOST=$databaseEmulatorHost" >> $GITHUB_ENV
-          echo "REACT_APP_FIRESTORE_EMULATOR_HOST=$emulatorHost" >> $GITHUB_ENV
-          echo "REACT_APP_FB_databaseURL=http://$databaseEmulatorHost?ns=$gcloudProject" >> $GITHUB_ENV
-          echo "GCLOUD_PROJECT=$gcloudProject" >> $GITHUB_ENV
-
-          # Generate Service Account file required to prevent credential error during functions unit tests (jq used to format)
-          echo "Generating Service Account File..."
-          echo "$(echo $SERVICE_ACCOUNT | jq .)" > $HOME/serviceAccount.json
-          echo "GOOGLE_APPLICATION_CREDENTIALS=$HOME/serviceAccount.json" >> $GITHUB_ENV
-
-          # Use Firebase SDK API to get the app's configuration and export to REACT_APP prefixed environment variables
-          # NOTE: databaseURL is intentionally removed since it is set above
-
-          # Use firebase SDK API to get the app's configuration and export to CYPRESS. NOTE: databaseURL is intentionally removed
-          firebaseConfig=$(npx firebase --project $gcloudProject apps:sdkconfig WEB \
-            $(npx firebase --project $gcloudProject apps:list WEB | grep $appName | awk '{ print $4}') | \
-              tr '\n' ' ' | \
-              sed 's/.*initializeApp(//g' | \
-              sed 's/);//g' | \
-              jq -r 'del(.databaseURL) | to_entries[] | [.key, (.value | tojson)] | join("::")' | \
-              sed 's/:"/:/g; s/^/echo \"REACT_APP_FB_/g' \
-          )
-
-          # Loop through each line of config and evaluate to export env vars
-          while IFS= read -r line; do
-            echo Evaluating: $line
-            eval $line >> $GITHUB_ENV
-          done <<< "$firebaseConfig"
+          bin/generate-firebase-sdk-config.js --file ./config/default.json
 
       - name: Verify App
         run: |
           <% if(useYarn) { %>yarn<% } else { %>npm run<% } %> lint # Check for lint in app code<% if(includeFunctionsTests) { %>
 
       - name: Unit Test Functions
+        env:
+          SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}
         run: |
-          <% if(useYarn) { %>yarn<% } else { %>npm run<% } %> functions:test:cov -- --project $GCLOUD_PROJECT # Run unit tests with coverage
+          # Throw a clear error if SERVICE_ACCOUNT secret is not set
+          if [ -z "$SERVICE_ACCOUNT" ];
+            then
+              missingTokenErrMsg="\"SERVICE_ACCOUNT\" github secret is required to load project configuration. Visit https://github.com/${{ github.repository }}/settings/secrets to set."
+              echo "::error ::$missingTokenErrMsg"
+              exit 1
+          fi
+
+          # Generate Service Account file required to prevent credential error in unit tests (jq used to format)
+          projectId=$(echo $SERVICE_ACCOUNT | jq .project_id)
+          serviceAccountId=$(echo $SERVICE_ACCOUNT | jq .private_key_id)
+
+          echo "Generating service account file for project \"$projectId\" with id \"$serviceAccountId\""
+          echo "$(echo $SERVICE_ACCOUNT | jq .)" > $HOME/serviceAccount.json
+          export GOOGLE_APPLICATION_CREDENTIALS="$HOME/serviceAccount.json"
+
+          echo "Setting emulator settings to environment..."
+          # Set variables to environment to be used in later steps
+          echo "FIREBASE_DATABASE_EMULATOR_HOST=$(cat firebase.json | jq .emulators.database.port)" >> $GITHUB_ENV
+          echo "FIRESTORE_EMULATOR_HOST=localhost:$(cat firebase.json | jq .emulators.firestore.port)" >> $GITHUB_ENV
+
+          # Run tests and generate coverage
+          <% if(useYarn) { %>yarn<% } else { %>npm run<% } %> functions:test:cov <% if(useYarn) { %>-- <% } %>--project $GCLOUD_PROJECT # Run unit tests with coverage
 
       - name: Upload Test Coverage For Functions
         # NOTE: Token will need to be added if using codecov with private repos
@@ -125,6 +122,15 @@ jobs:
       - name: Build App
         run: |
           <% if(useYarn) { %>yarn<% } else { %>npm run<% } %> build
+
+      - name: Deploy to Firebase hosting preview channel
+        uses: FirebaseExtended/action-hosting-deploy@v0
+        id: preview-deploy
+        with:
+          repoToken: "${{ secrets.GITHUB_TOKEN }}"
+          firebaseServiceAccount: "${{ secrets.SERVICE_ACCOUNT }}"
+          expires: 7d
+          projectId: ${{ env.GCLOUD_PROJECT }}
 
       - name: Archive Build Artifact
         uses: actions/upload-artifact@v2
@@ -143,7 +149,7 @@ jobs:
       - name: Setup Node
         uses: actions/setup-node@v2.1.5
         with:
-          node-version: 12
+          node-version: 14
 
       - name: Get Library Versions For Binary Caching
         id: cache-settings
@@ -177,50 +183,26 @@ jobs:
           <% if(useYarn) { %>yarn install --frozen-lockfile<% } else { %>npm ci<% } %>
           $(<% if(useYarn) { %>yarn<% } else { %>npm<% } %> bin)/cypress verify
 
-      - name: Set Test Environment Settings
-        env:
-          SERVICE_ACCOUNT: ${{ secrets.MASTER_SERVICE_ACCOUNT }}
-          FIREBASE_APP_NAME: ${{ secrets.FIREBASE_APP_NAME }}
-          GITHUB_HEAD_REF: ${{ github.head_ref }}
-          GITHUB_REF: ${{ github.ref }}
+      - name: Set environment
         run: |
-          set -o pipefail
-
+          # Get branch name from github ref (i.e. refs/heads/master -> master)
           gitBranch=${GITHUB_REF##*/}
+
+          # Find the config associated to the firebase project in .firebaserc (falling back to default)
           gcloudProject=$(cat .firebaserc | jq -r --arg alias "$gitBranch" '.projects[$alias] // .projects.default')
-          echo "Setting environment for branch: $gitBranch and project: $gcloudProject"
-  
-          echo "Setting emulator settings to environment..."
-          databaseEmulatorHost=localhost:$(cat firebase.json | jq .emulators.database.port)
-          emulatorHost=localhost:$(cat firebase.json | jq .emulators.firestore.port)
+          appName=<%= appName %>
+
+          echo "Setting environment for branch: $gitBranch, project: $gcloudProject, and app: $appName..."
 
           # Set variables to environment to be used in later steps
-          echo "FIREBASE_DATABASE_EMULATOR_HOST=$databaseEmulatorHost" >> $GITHUB_ENV
-          echo "FIRESTORE_EMULATOR_HOST=$emulatorHost" >> $GITHUB_ENV
-          echo "CYPRESS_BASE_URL=http://localhost:$(cat package.json | jq .config.port)" >> $GITHUB_ENV
-          echo "CYPRESS_FB_databaseURL=http://$databaseEmulatorHost?ns=$gcloudProject" >> $GITHUB_ENV
           echo "GCLOUD_PROJECT=$gcloudProject" >> $GITHUB_ENV
-  
-          # Generate Service Account file required to prevent credential error during functions unit tests (jq used to format)
-          echo "Generating Service Account File..."
-          echo "$(echo $SERVICE_ACCOUNT | jq .)" > $HOME/serviceAccount.json
-          echo "GOOGLE_APPLICATION_CREDENTIALS=$HOME/serviceAccount.json" >> $GITHUB_ENV
+          echo "NODE_CONFIG_ENV=$branch" >> $GITHUB_ENV
+          echo "ENV=$branch" >> $GITHUB_ENV
 
-          # Use firebase SDK API to get the app's configuration and export to CYPRESS. NOTE: databaseURL is intentionally removed
-          firebaseConfig=$(npx firebase --project $gcloudProject apps:sdkconfig WEB \
-            $(npx firebase --project $gcloudProject apps:list WEB | grep $FIREBASE_APP_NAME | awk '{ print $4}') | \
-              tr '\n' ' ' | \
-              sed 's/.*initializeApp(//g' | \
-              sed 's/);//g' | \
-              jq -r 'del(.databaseURL) | to_entries[] | [.key, (.value | tojson)] | join("::")' | \
-              sed 's/:"/:/g; s/^/echo \"CYPRESS_FIREBASE_/g' \
-          )
-
-          # Loop through each line of config and evaluate to export env vars
-          while IFS= read -r line; do
-            echo Evaluating: $line
-            eval $line >> $GITHUB_ENV
-          done <<< "$firebaseConfig"
+      - name: Generate Firebase SDK config for ${{ env.GCLOUD_PROJECT }}
+        env:
+          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
+        run: bin/generate-firebase-sdk-config.js --file ./config/default.json
 
       # Download Built app since we are testing locally
       - name: Download Build Artifact
@@ -243,7 +225,6 @@ jobs:
         env:
           # pass the Dashboard record key as an environment variable
           CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_KEY }}
-          CYPRESS_TEST_UID: ${{ secrets.TEST_UID }}
           SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}
           GITHUB_HEAD_REF: ${{ github.head_ref }}
           GITHUB_REF: ${{ github.ref }}<% } %>
