v7.0.0 (#250)
* feat(functions): drop support for firebase-functions versions older than v1 in functions sub-generator
* feat(app): switch react component files to jsx
* feat(app): add option to use typescript for cloud functions
* feat(app): add dark mode with loading of system preference from UserAgent
* feat(app): add [notistack](https://github.com/iamhosseindhv/notistack/) for multiple notification support
* feat(app): add dependabot config for npm and github actions dependencies
* feat(functions): use `functions.source` setting from `firebase.json` if it is set (common in mono-repos)
* chore(app): remove containers folder
* chore(functions): remove async utilities in favor of try/catch
* chore(app): update github actions version including cache and cypress
* chore(app): update dependencies within github actions (including cache and cypress)

diff --git a/examples/react-firestore/.github/workflows/verify.yml b/examples/react-firestore/.github/workflows/verify.yml
--- a/examples/react-firestore/.github/workflows/verify.yml
+++ b/examples/react-firestore/.github/workflows/verify.yml
@@ -27,13 +27,13 @@ jobs:
           echo "::set-output name=firebase-tools::$(yarn list -s --depth=0 --pattern firebase-tools | tail -n 1 | sed 's/.*@//g')"
 
       - name: Cache Firebase Emulator Binaries
-        uses: actions/cache@v1
+        uses: actions/cache@v2
         with:
           path: ~/.cache/firebase/emulators
           key: ${{ runner.os }}-firebase-${{ steps.cache-settings.outputs.firebase-tools }}
 
       - name: Cache App Dependencies
-        uses: actions/cache@v1
+        uses: actions/cache@v2
         with:
           path: ${{ steps.cache-settings.outputs.dir }}
           key: ${{ runner.os }}-app-${{ hashFiles('yarn.lock') }}
@@ -109,16 +109,14 @@ jobs:
         run: |
           yarn lint # Check for lint in app code
 
-      # NOTE: Skipped because of "Channel credentials must be a ChannelCredentials object" error from firebase-admin
-      # See https://github.com/firebase/firebase-tools/issues/2207 for more info
-      # - name: Unit Test Functions
-      #   run: |
-      #     yarn functions:test:cov -- --project $GCLOUD_PROJECT # Run unit tests with coverage
+      - name: Unit Test Functions
+        run: |
+          yarn functions:test:cov -- --project $GCLOUD_PROJECT # Run unit tests with coverage
 
-      # - name: Upload Test Coverage For Functions
-      #   # NOTE: Token will need to be added if using codecov with private repos
-      #   run: |
-      #     bash <(curl -s https://codecov.io/bash) -f functions/coverage/lcov.info || echo 'Codecov failed to upload'
+      - name: Upload Test Coverage For Functions
+        # NOTE: Token will need to be added if using codecov with private repos
+        run: |
+          bash <(curl -s https://codecov.io/bash) -f functions/coverage/lcov.info || echo 'Codecov failed to upload'
 
       - name: Build Functions
         run: |
@@ -155,19 +153,19 @@ jobs:
           echo "::set-output name=cypress::$(yarn list -s --depth=0 --pattern cypress | tail -n 1 | sed 's/.*@//g')"
 
       - name: Cache Firebase Emulator Binaries
-        uses: actions/cache@v1
+        uses: actions/cache@v2
         with:
           path: ~/.cache/firebase/emulators
           key: ${{ runner.os }}-firebase-${{ steps.cache-settings.outputs.firebase-tools }}
 
       - name: Cache Cypress Binary
-        uses: actions/cache@v1
+        uses: actions/cache@v2
         with:
           path: ~/.cache/Cypress
           key: ${{ runner.os }}-cypress-${{ steps.cache-settings.outputs.cypress }}
 
       - name: Cache App Dependencies
-        uses: actions/cache@v1
+        uses: actions/cache@v2
         with:
           path: ${{ steps.cache-settings.outputs.dir }}
           key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
@@ -235,7 +233,7 @@ jobs:
       # This stage tests a version of the app which is running locally in the
       # container on port 3000.
       - name: Cypress Run
-        uses: cypress-io/github-action@v1
+        uses: cypress-io/github-action@v2
         with:
           record: true
           start: yarn emulators:hosting --project ${{ env.GCLOUD_PROJECT }}
diff --git a/generators/app/templates/.github/workflows/verify.yml b/generators/app/templates/.github/workflows/verify.yml
--- a/generators/app/templates/.github/workflows/verify.yml
+++ b/generators/app/templates/.github/workflows/verify.yml
@@ -8,7 +8,7 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - name: Cancel Previous Runs
-        uses: styfle/cancel-workflow-action@0.4.0
+        uses: styfle/cancel-workflow-action@0.4.1
         with:
           access_token: ${{ github.token }}
 
@@ -16,7 +16,7 @@ jobs:
         uses: actions/checkout@v2
 
       - name: Setup Node
-        uses: actions/setup-node@v1
+        uses: actions/setup-node@v2.1.1
         with:
           node-version: 12<% if(useYarn) { %>
 
@@ -27,13 +27,13 @@ jobs:
           echo "::set-output name=firebase-tools::$(yarn list -s --depth=0 --pattern firebase-tools | tail -n 1 | sed 's/.*@//g')"
 
       - name: Cache Firebase Emulator Binaries
-        uses: actions/cache@v1
+        uses: actions/cache@v2.1.0
         with:
           path: ~/.cache/firebase/emulators
           key: ${{ runner.os }}-firebase-${{ steps.cache-settings.outputs.firebase-tools }}<% } %><% } %>
 
       - name: Cache App Dependencies
-        uses: actions/cache@v1
+        uses: actions/cache@v2.1.0
         with:
           path: <% if(!useYarn) { %>~/.npm<% } else { %>${{ steps.cache-settings.outputs.dir }}<% } %>
           key: ${{ runner.os }}-app-${{ hashFiles('<% if(useYarn) { %>yarn.lock<% } else { %>package-lock.json<% } %>') }}
@@ -109,16 +109,14 @@ jobs:
         run: |
           <% if(useYarn) { %>yarn<% } else { %>npm run<% } %> lint # Check for lint in app code<% if(includeFunctionsTests) { %>
 
-      # NOTE: Skipped because of "Channel credentials must be a ChannelCredentials object" error from firebase-admin
-      # See https://github.com/firebase/firebase-tools/issues/2207 for more info
-      # - name: Unit Test Functions
-      #   run: |
-      #     <% if(useYarn) { %>yarn<% } else { %>npm run<% } %> functions:test:cov -- --project $GCLOUD_PROJECT # Run unit tests with coverage
+      - name: Unit Test Functions
+        run: |
+          <% if(useYarn) { %>yarn<% } else { %>npm run<% } %> functions:test:cov -- --project $GCLOUD_PROJECT # Run unit tests with coverage
 
-      # - name: Upload Test Coverage For Functions
-      #   # NOTE: Token will need to be added if using codecov with private repos
-      #   run: |
-      #     bash <(curl -s https://codecov.io/bash) -f functions/coverage/lcov.info || echo 'Codecov failed to upload'<% } %>
+      - name: Upload Test Coverage For Functions
+        # NOTE: Token will need to be added if using codecov with private repos
+        run: |
+          bash <(curl -s https://codecov.io/bash) -f functions/coverage/lcov.info || echo 'Codecov failed to upload'<% } %>
 
       - name: Build Functions
         run: |
@@ -143,7 +141,7 @@ jobs:
         uses: actions/checkout@v2
 
       - name: Setup Node
-        uses: actions/setup-node@v1
+        uses: actions/setup-node@v2.1.1
         with:
           node-version: 12
 
@@ -155,19 +153,19 @@ jobs:
           echo "::set-output name=cypress::$(yarn list -s --depth=0 --pattern cypress | tail -n 1 | sed 's/.*@//g')"
 
       - name: Cache Firebase Emulator Binaries
-        uses: actions/cache@v1
+        uses: actions/cache@v2.1.0
         with:
           path: ~/.cache/firebase/emulators
           key: ${{ runner.os }}-firebase-${{ steps.cache-settings.outputs.firebase-tools }}
 
       - name: Cache Cypress Binary
-        uses: actions/cache@v1
+        uses: actions/cache@v2.1.0
         with:
           path: ~/.cache/Cypress
           key: ${{ runner.os }}-cypress-${{ steps.cache-settings.outputs.cypress }}
 
       - name: Cache App Dependencies
-        uses: actions/cache@v1
+        uses: actions/cache@v2.1.0
         with:
           path: ${{ steps.cache-settings.outputs.dir }}
           key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
@@ -235,7 +233,7 @@ jobs:
       # This stage tests a version of the app which is running locally in the
       # container on port 3000.
       - name: Cypress Run
-        uses: cypress-io/github-action@v1
+        uses: cypress-io/github-action@v2
         with:
           record: true
           start: <% if(useYarn) { %>yarn<% } else { %>npm run<% } %> emulators:hosting<% if(!useYarn) { %> --<% } %> --project ${{ env.GCLOUD_PROJECT }}
